# Generated by Django 4.1.5 on 2023-01-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marca', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.CharField(max_length=200)),
                ('item_ya_usado', models.CharField(max_length=200)),
            ],
        ),
    ]
